version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estospaces-web
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXT_PUBLIC_APP_NAME: EstoSpaces
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
      NEXT_PUBLIC_CORE_SERVICE_URL: http://localhost:8080
      NEXT_PUBLIC_BOOKING_SERVICE_URL: http://localhost:8081
      NEXT_PUBLIC_PAYMENT_SERVICE_URL: http://localhost:8082
      NEXT_PUBLIC_PLATFORM_SERVICE_URL: http://localhost:8083
    ports:
      - "3000:3000"
    restart: unless-stopped
